### ISSUE TITLE
Build / Run Job fails on jobs with tSnowflakeOutput and huge tables

### ISSUE THREAD

**Issue by swiffer** [Talend/components#1312]
After migrating to Talend OS DI 7.0.1 jobs containing tSnowflakeOutput component with huge tables (400 columns+) no longer build successfully

```log
Caused by: org.eclipse.emf.codegen.jet.JETException: InvocationTargetException
	at org.eclipse.emf.codegen.jet.JETEmitter.generate(JETEmitter.java:469)
	at org.talend.designer.codegen.config.TalendJetEmitter.generate(TalendJetEmitter.java:684)
	at org.eclipse.emf.codegen.jet.JETEmitter.generate(JETEmitter.java:441)
	at org.eclipse.emf.codegen.jet.JETEmitter.generate(JETEmitter.java:432)
	at org.talend.designer.codegen.proxy.JetProxy.generate(JetProxy.java:54)
	at org.talend.designer.codegen.CodeGenerator.generateComponentCode(CodeGenerator.java:821)
	... 48 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.emf.codegen.jet.JETEmitter.generate(JETEmitter.java:461)
	... 53 more
Caused by: java.lang.StackOverflowError
	at java.util.regex.Pattern$GroupTail.match(Unknown Source)
	at java.util.regex.Pattern$BmpCharProperty.match(Unknown Source)
	at java.util.regex.Pattern$NotBehind.match(Unknown Source)
	at java.util.regex.Pattern$Curly.match1(Unknown Source)
	at java.util.regex.Pattern$Curly.match(Unknown Source)
	at java.util.regex.Pattern$BmpCharProperty.match(Unknown Source)
	at java.util.regex.Pattern$NotBehind.match(Unknown Source)
	at java.util.regex.Pattern$GroupHead.match(Unknown Source)
	at java.util.regex.Pattern$Start.match(Unknown Source)
	at java.util.regex.Matcher.search(Unknown Source)
	at java.util.regex.Matcher.find(Unknown Source)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:314)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
	...
        ...
        ...
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
	at org.talend.core.utils.TalendQuoteUtils.filterQuote(TalendQuoteUtils.java:319)
```

**Comment by wwang-talend** [comment]
shoud have been fixed here : https://jira.talendforge.org/browse/TDI-40329

**Comment by swiffer** [comment]
@wwang-talend thanks responding so quickly! Sadly I cannot see it as I've no login to Jira on Talendforge.

Is a workaround available or do I need to wait for the next version?

**Comment by wwang-talend** [comment]
no workaround here, the next version 7.0.2 or 7.1.1 will be ok.

**Comment by swiffer** [comment]
Ok, confirmed working in 7.1.1M1! Thanks
